# **Beginners' Hypothesis**

Anish Kumar\
21322006

In [1]:
''' TO IMPORT DRIVE FROM GOOGLE DRIVE. NOT REQUIRED IF USING OTHER IDE '''

from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

Main Code

In [2]:
''' IMPORTING NUMPY AND PANDAS MODULES '''

import numpy as np
import pandas as pd

In [3]:
loc1 = '/content/drive/MyDrive/Colab Notebooks/weather_train.csv'
loc2 = '/content/drive/MyDrive/Colab Notebooks/weather_test.csv'

train_data = pd.read_csv(loc1, index_col=0)
test_data = pd.read_csv(loc2, index_col=0)

This will read both CSV files from drive (can be changed as per requirement). train_data stores training data which will be used to fit the ML model and test_data will be used to test the model

In [4]:
train_data      # To view full file

,DATE (YYYY/MM/DD),MST,Global CMP22 (vent/cor) [W/m^2],Direct sNIP [W/m^2],Azimuth Angle [degrees],Tower Dry Bulb Temp [deg C],Tower Wet Bulb Temp [deg C],Tower Dew Point Temp [deg C],Tower RH [%],Peak Wind Speed @ 6ft [m/s],Avg Wind Direction @ 6ft [deg from N],Station Pressure [mBar],Precipitation (Accumulated) [mm],Moisture,Albedo (CMP11),Cloud Type,Solar Zenith Angle,Snow Depth [cm]
0,2020/02/22,04:11,-1.12724,-0.365968,77.66760,8.210,0.388,-12.412,19.20,1.20,300.10,817.297,0.000,0.0,0.0000,0,50.16,9.460
1,2020/07/25,20:10,-1.04030,0.093816,304.73416,20.140,14.855,11.955,59.29,4.45,262.40,820.184,5.334,0.0,0.0000,7,57.39,1.121
2,2020/09/13,04:03,-1.29707,-0.251820,68.24852,14.080,6.560,-0.940,35.17,2.45,280.20,822.653,0.000,0.0,0.0000,8,65.63,-0.050
3,2020/03/08,15:25,79.20020,-0.014836,237.11811,15.030,5.725,-4.575,24.36,3.70,23.07,809.641,0.000,0.0,0.1587,6,57.08,0.734
4,2020/11/17,19:33,-1.61485,-0.459201,271.20406,12.660,3.180,-10.220,17.37,2.70,283.80,818.717,0.000,0.0,0.0000,0,128.59,0.013
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14995,2020/04/20,18:47,3.69585,-0.553937,286.76511,13.280,5.410,-3.090,30.95,1.20,35.00,815.183,0.000,0.0,0.0000,0,91.76,0.954
14996,2020/10/12,09:00,515.44400,912.832000,131.12291,16.980,5.677,-8.323,15.55,8.20,302.50,817.411,0.000,0.0,0.2326,0,44.57,-0.277
14997,2020/12/31,09:20,286.39400,872.952000,140.97204,3.642,-1.619,-10.419,31.52,0.00,0.00,812.671,0.000,0.0,0.5277,3,82.88,2.426
14998,2020/06/06,00:25,-1.38846,0.064190,6.62879,23.580,11.528,1.928,24.13,3.45,242.80,813.969,0.000,0.0,0.0000,0,133.73,0.777
14999,2020/09/04,15:57,435.38100,765.540000,254.74761,29.940,13.579,0.819,15.33,3.20,25.15,823.665,0.000,0.0,0.2181,1,54.06,0.342

In [5]:
test_data

,DATE (YYYY/MM/DD),MST,Global CMP22 (vent/cor) [W/m^2],Direct sNIP [W/m^2],Azimuth Angle [degrees],Tower Dry Bulb Temp [deg C],Tower Wet Bulb Temp [deg C],Tower Dew Point Temp [deg C],Tower RH [%],Peak Wind Speed @ 6ft [m/s],Avg Wind Direction @ 6ft [deg from N],Station Pressure [mBar],Precipitation (Accumulated) [mm],Moisture,Albedo (CMP11),Cloud Type,Solar Zenith Angle
0,23/01/20,19:55,-0.821587,-0.197822,270.39668,0.344,-3.269,-9.469,43.43,1.95,300.70,817.643,0.000,0.0,0.0000,7,163.53
1,05/02/20,04:13,-0.464099,0.039564,83.18453,-15.420,-16.249,-19.649,67.07,1.20,308.30,809.469,0.000,0.0,0.0000,0,84.09
2,06/06/20,02:25,-1.133330,-0.009875,35.33772,22.380,11.522,3.122,28.25,1.70,214.00,813.392,0.000,0.0,0.0000,7,109.24
3,10/05/20,14:17,849.620000,946.128000,244.34737,14.240,6.585,-1.215,34.02,3.45,45.53,821.467,0.000,0.0,0.1844,7,156.80
4,11/12/20,15:41,44.193400,0.488831,230.89280,-5.580,-6.169,-7.269,86.40,1.20,15.69,812.324,0.000,1.0,0.6648,7,154.89
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2401,16/11/20,21:21,-1.444170,-0.360447,292.96778,9.820,3.214,-4.886,33.41,1.70,272.00,824.536,0.000,0.0,0.0000,7,52.08
2402,26/12/20,11:17,490.631000,996.863000,168.59312,14.500,3.446,-13.654,11.30,2.45,154.90,811.310,0.000,0.0,0.2381,3,75.61
2403,09/04/20,00:08,-0.957105,-0.143412,1.93913,6.984,2.890,-1.610,53.41,2.70,22.43,820.148,0.000,0.0,0.0000,3,108.22
2404,16/12/20,11:37,502.869000,978.244000,174.94429,4.311,-1.305,-10.505,29.84,8.70,287.10,814.018,0.000,0.0,0.6220,7,9.83
2405,25/05/20,13:16,667.554000,278.366000,227.66108,15.310,7.691,0.591,36.65,1.95,265.60,818.302,0.508,0.0,0.1547,0,42.60

In [6]:
train_data.info()       # Checking for any null values and datatypes

<class 'pandas.core.frame.DataFrame'>
Int64Index: 15000 entries, 0 to 14999
Data columns (total 18 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   DATE (YYYY/MM/DD)                      15000 non-null  object
 1   MST                                    15000 non-null  object
 2   Global CMP22 (vent/cor) [W/m^2]        15000 non-null  float64
 3   Direct sNIP [W/m^2]                    15000 non-null  float64
 4   Azimuth Angle [degrees]                15000 non-null  float64
 5   Tower Dry Bulb Temp [deg C]            15000 non-null  float64
 6   Tower Wet Bulb Temp [deg C]            15000 non-null  float64
 7   Tower Dew Point Temp [deg C]           15000 non-null  float64
 8   Tower RH [%]                           15000 non-null  float64
 9   Peak Wind Speed @ 6ft [m/s]            15000 non-null  float64
 10  Avg Wind Direction @ 6ft [deg from N]  15000 non-null  float64
 11  Station Pressure [mBar]                15000 non-null  float64
 12  Precipitation (Accumulated) [mm]       15000 non-null  float64
 13  Moisture                               15000 non-null  float64
 14  Albedo (CMP11)                         15000 non-null  float64
 15  Cloud Type                             15000 non-null  int64
 16  Solar Zenith Angle                     15000 non-null  float64
 17  Snow Depth [cm]                        15000 non-null  float64
dtypes: float64(15), int64(1), object(2)
memory usage: 2.2+ MB

In [7]:
train_data.columns      # Gives all the column, which can be used to copy directly then paste as features and targeted column

Index(['DATE (YYYY/MM/DD)', 'MST', 'Global CMP22 (vent/cor) [W/m^2]',
       'Direct sNIP [W/m^2]', 'Azimuth Angle [degrees]',
       'Tower Dry Bulb Temp [deg C]', 'Tower Wet Bulb Temp [deg C]',
       'Tower Dew Point Temp [deg C]', 'Tower RH [%]',
       'Peak Wind Speed @ 6ft [m/s]', 'Avg Wind Direction @ 6ft [deg from N]',
       'Station Pressure [mBar]', 'Precipitation (Accumulated) [mm]',
       'Moisture', 'Albedo (CMP11)', 'Cloud Type', 'Solar Zenith Angle',
       'Snow Depth [cm]'],
      dtype='object')

Now all the work on the CSV file is done and is ready for model.

In [8]:
''' IMPORTING CLASSES FROM Scikit Learn MODULE '''

from sklearn.tree import DecisionTreeRegressor as dtr
from sklearn.metrics import mean_absolute_error as mae
from sklearn.model_selection import train_test_split as tts

As seen, I will be using Decision Tree method

In [9]:
features = ['Global CMP22 (vent/cor) [W/m^2]',
       'Direct sNIP [W/m^2]', 'Azimuth Angle [degrees]',
       'Tower Dry Bulb Temp [deg C]', 'Tower Wet Bulb Temp [deg C]',
       'Tower Dew Point Temp [deg C]', 'Tower RH [%]',
       'Peak Wind Speed @ 6ft [m/s]', 'Avg Wind Direction @ 6ft [deg from N]',
       'Station Pressure [mBar]', 'Precipitation (Accumulated) [mm]',
       'Moisture', 'Albedo (CMP11)', 'Cloud Type', 'Solar Zenith Angle']
X = train_data[features]
y = train_data[['Snow Depth [cm]']]

We have created 'X' as features list and 'y' is our targeted column

In [10]:
train_X, test_X, train_y, test_y = tts(X, y, random_state=0)

This will divide the training data into two parts one for fitting (train_X and train_y) and other to check the accuracy of the model (test_X and test_y)

In [11]:
decision_model = dtr(random_state=1)        # This will create model of Decision Tree
decision_model.fit(train_X, train_y)        # train_X and train_y are given to fit

DecisionTreeRegressor(random_state=1)

In [12]:
predict_for_error_check = decision_model.predict(test_X)
decision_error = mae(predict_for_error_check, test_y)
print(decision_error)

9.227945866666666

This is the mean absolute error made by the ML model when using decision tree. We can further optimize it by providing the number of splits.

** To give number of splits manually, I will use hit and trial method **

In [13]:
def mean_abs_err(leaf, train_X, test_X, train_y, test_y):
    model = dtr(max_leaf_nodes=leaf, random_state=1)
    model.fit(train_X, train_y)
    return (mae(model.predict(test_X), test_y))

This function will return the mean absolute error of decision tree with the provided number of splits

In [14]:
def get_key(inp_dict, min_ele):
    key_list = list(inp_dict.keys())
    val_list = list(inp_dict.values())
    position = val_list.index(min_ele)
    return(key_list[position])

This function will return the key for minimum value from the dictionary dict_of_error

In [15]:
leaf_lst = range(100, 10000, 100)
dict_of_error = dict()
for leaf in leaf_lst:
    error = mean_abs_err(leaf, train_X, test_X, train_y, test_y)
    dict_of_error[leaf] = error
print(min(dict_of_error.values()))      # This will give the minimum error for elements in leaf_lst
leaf = get_key(dict_of_error, min(dict_of_error.values()))      #  This will extract the number of splits
print(leaf)     # This is in a set

9.211065900288242
1700

Here, we can see when there are 1700 splits, the model is better fitted. So we will create new model using this number of splits.

In [16]:
X_ = test_data[features]
new_model = dtr(max_leaf_nodes = leaf, random_state=1)
new_model.fit(train_X, train_y)
prediction = new_model.predict(X_)      # Our better prediction

Now we will produce the CSV file

In [17]:
Id = np.arange(0, prediction.size)

In [18]:
output = pd.DataFrame({'Id':Id , 'Snow Depth [cm]': prediction})
output.to_csv('/content/drive/MyDrive/Colab Notebooks/submitted_file.csv', index=False)      # This line will generate submission CSV file